name: Changelog Check

on:
  # TODO: Experimental
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # TODO: Needed for pull_request_target
          ref: ${{ github.event.pull_request.head.sha }}  # Check out PR's actual code

      - name: Check Changelog
        uses: solrbot/logchange-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          changelog-path: changelog/unreleased
          on-missing-entry: generate
          claude-token: ${{ secrets.CLAUDE_API_KEY }}
          skip-files-regex: '^(README\.md|docs/|\.github/)'
