name: Changelog Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Changelog
        uses: solrbot/logchange-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          changelog-path: changelog/unreleased
          on-missing-entry: warn
          # skip-files-regex: '^(README\.md|docs/|\.github/)'
          # For AI generation:
          # on-missing-entry: generate
          # claude-token: ${{ secrets.CLAUDE_API_KEY }}
