name: Changelog Check

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  # NOTE: Using pull_request_target allows this workflow to comment on PRs from forks
  # and use full GITHUB_TOKEN permissions. Security: We explicitly check out the PR's
  # actual code (head.sha), not untrusted base, preventing arbitrary code execution
  # on the repository. Token scope limited to pull-requests:write only.

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}  # Check out PR's actual code

      - name: Check Changelog
        uses: solrbot/logchange-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          changelog-path: changelog/unreleased
          on-missing-entry: generate
          claude-token: ${{ secrets.CLAUDE_API_KEY }}
          skip-files-regex: '^(README\.md|docs/|\.github/)'
